checkers-dev
tomOsuch/checkers-kodilla pull request #1
Opened 2020-09-22 12:19 UTC by tomOsuch

2020-09-22 21:12 UTC, marszelun requested changes
Uwagi ogólne:
1. klasy z pakietu `gamelogic` zależą od klas z pakietu `gameio`. Tak nie powinno być, bo znów logika miesza się z wyświetlaniem.
2. Dobrze, jakbyś miał wydzieloną klasę, sterującą przepływem gry. 
3. Nie do końca rozumiem odpowiedzialności poszczególnych klas. Chciałbym omówić to na video, ale potrzebuję się do tego przygotować. Czy możesz w jednym zdaniu opisać mi (może być w odpowiedzi na ten komentarz) odpowiedzialności poszczególnych klas w projekcie? Jedno zdanie na klasę. jeśli nie da się w jednym zdaniu tego opisać, to znaczy że klasa ma zbyt wiele odpowiedzialności ;)

2020-09-23 19:41 UTC, tomOsuch commented
> Uwagi ogólne:
> 
> 1. klasy z pakietu `gamelogic` zależą od klas z pakietu `gameio`. Tak nie powinno być, bo znów logika miesza się z wyświetlaniem.
> 2. Dobrze, jakbyś miał wydzieloną klasę, sterującą przepływem gry.
> 3. Nie do końca rozumiem odpowiedzialności poszczególnych klas. Chciałbym omówić to na video, ale potrzebuję się do tego przygotować. Czy możesz w jednym zdaniu opisać mi (może być w odpowiedzi na ten komentarz) odpowiedzialności poszczególnych klas w projekcie? Jedno zdanie na klasę. jeśli nie da się w jednym zdaniu tego opisać, to znaczy że klasa ma zbyt wiele odpowiedzialności ;)

Ok to po kolei będę opisywał jakie były założenia dla poszczególnych klas i jakie mają odpowiedzialności.
1. Piece - Klasa odpowiedzialna za konstrukcję pionka
2. BoardIO - Klasa odpowiedzialna za rysowanie planszy do gry wraz z pionkami (wywołanie metody rysowania pionków z klasy Piece)
3. BoardPosition - Klasa odpowiedzialna za pozycję pionka i jego trasę
4.  Board - Klasa zawierająca tabelę danych pionków wraz z metodami pomocniczymi
BoardLogic - Klasa implementująca podstawową logikę gry
PlayerAI - Klasa z logiką sztucznej inteligencji

2020-09-24 22:12 UTC, marszelun requested changes

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gameio/BoardIO.java
> +public class BoardIO {
Spróbuj stworzyć interfejs, który ta klasa będzie implementować, ale również będzie można np. zrobić również wersję konsolową gry w oparciu o ten sam interfejs.
Tu kilka podpowiedzi:
```
interface Board {
    void addPiece(Piece piece, BoardPosition position); //dodaje pionek - używane przy inicjalizacji
    void movePiece(Piece piece, BoardPosition targetPosition); //przemieszcze pionek na nową pozycję
    void removePiece(BoardPosition position); //usuwa pionek ze wskazanej pozycji (przy biciu)
    void highglihtPossibleMoves(List<BoardPosition> possibleMoves); //oznacza pola, na które można się przemieścić
    void removeHighlight(); //usuwa podświetlenie
}
```
Zauważ:
- wszystkie metody są void - tej klasie tylko wydajesz komendy, niczego z niej nie wyciągasz (pamiętasz wzorzec Redux i jednokierunkowy przepływ informacji?)
- możesz rozważyć, czy warto / potrzeba trzymać `BoardPosition` jako pole w `Piece` (czyli pionek "wie", na jakiej jest pozycji) - wtedy metoda `addPiece` potrzebuje tylko pionka i nie potrzebuje pozycji (bo pozycja jest już w pionku)
- klasa implementująca `Board` może jednocześnie rozszerzać komponent graficzny, dzięki temu utworzysz tylko jej obiekt w klasie startowej i dodasz na scenę. Cała inicjalizacja wyglądu może odbywać się w konstruktorze.
- nie potrzeba tutaj handlera zdarzeń myszy, bo funkcjonalność przesuwania zapewni Ci handler kliku w pionku (z dokładnością do klikania w zaznaczone pole - nie pamiętam czy to ma być przeciąganie, czy ponowny klik)

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gameio/Piece.java
> +    private boolean color;
Zamiast kompozycji proponuję tutaj wykorzystanie dziedziczenia. 
```
BlackCrown extends BlackPiece extends Piece
WhiteCrown extends WhitePiece extends Piece
```
Nie potrzebujesz wtedy ani pola `color`, ani `crown` (pole `empty` - nie wiem do czego służy w klasie pionka. Co to jest pusty pionek??). Dodatkowo `Piece extends ImageView` (lub inny komponent graficzny) i w konstruktorze określasz jego wygląd, umiejętnie wywołując `super` lub w inny sposób inicjalizując obiekt graficzny rodzica.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +        primaryScene.setOnMouseClicked(
Tak jak rozmawialiśmy - spróbuj zamienić handler kliku myszą gdziekolwiek na handler kliku w pionek.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/Board.java
> +    private Piece[][] pieces;
Tu podstawowy błąd polega na korzystaniu z komponentów graficznych w klasie z logiką. Jednak jeśli zrobisz jakiś interfejs na `Piece`, który nie będzie miał żadnego powiązania z JavaFX, to może to być nawet OK.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/Board.java
> +    public Board(int _sideCount, int _startCount) {
Cóż to za dziwna konwencja nazewnicza z `_` na początku?

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/Board.java
> +                pieces[sideCount - 1 - i][sideCount - 1 - j].setWhite();
Zamiast dwóch pętli, wystarczy jedna i w zależności od współrzędnych, `new WhitePiece()` lub `new BlackPiece()`

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/Board.java
> +public class Board {
Pomyśl ogólnie o interfejsie tej klasy. Jakie metody są tu potrzebne? Jaki jest w ogóle sens tej klasy? Dla mnie wygląda ona na nie do końca sprecyzowane ogniwo między `BoardIO` i `BoardLogic`. Wszystko co tu jest mogłoby być IMHO w `BoardLogic`.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/BoardLogic.java
> +public class BoardLogic {
Spytam przewrotnie, co to jest logika planszy? Logika raczej przynależy do _gry_, nie do _planszy_.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/BoardLogic.java
> +public class BoardLogic {
+ ponownie zastanówmy się nad interfejsem. Widzę tutaj potrzebę następujących metod:
```
void initialize(); //inicjalizuje planszę (ustawia pionki na pozycjach startowych)
Set<BoardPosition> getPossibleMoves(BoardPosition boardPosition); //zwraca listę dopuszczalnych ruchów pionka znajdującego się na `BoardPosition`
MoveResult move(BoardPosition from, BoardPosition to); //przesuwa pionek i zwraca rezultat, rzuca wyjątek jeśli próbowano wykonać niedozwolony ruch - powinno to być jednak zablokowane na poziomie GUI
GameResult getGameResult(); //zwraca bieżący wynik gry
```
`MoveResult` może być pojemnikiem na kilka faktów występujących po wykonaniu ruchu:
```
class MoveResult {
    BoardPosition takenPiece; //pozycja zbitego pionka lub null, jeśli nic nie zostało zbite
    boolean furtherMovePossible; //czy możliwy jest dalszy ruch (po biciu)
    boolean shouldConvertToCrown; //czy pionek powinien być zamieniony na królową
}
```

Metody z `GameLogic` powinny być wywoływane przez klasę sterującą przepływem gry, a wartości z nich zwracane używane w wywołaniach do `BoardIO`, wykonywanych przez klasę sterującą przepływem gry.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/BoardPosition.java
> +    public List<BoardPosition> route;
Czy tutaj chodzi o ruch wielokrotny? Jeśli tak, to to jest trudna abstrakcja - nie będzie łatwiej (i prościej dla gracza) zaimplementować to tak, że po wykonaniu bicia po prostu jeśli są możliwości, to możesz wykonać tak jakby kolejny ruch.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/GameTreeNode.java
> +public class GameTreeNode {
Ta klasa jest bardzo abstrakcyjna. Jeśli używasz jej do wyznaczenia najdłuższej ścieżki dla komputera, to warto zamknąć to w jakimś pakiecie i nadać temu konkretniejszą nazwę.

2020-09-24 22:12 UTC, marszelun commented on src/main/java/com/kodilla/checkers/gamelogic/PlayerAI.java
> +        List<BoardPosition> moves = node.getData().getBoardLogic().longestAvailableMoves(1, !node.getData().getLastColor());
Widzę, że na prawdę chcesz tu realizować AI ;)
Proszę skup się na właściwym flow i designie kodu - wystarczy że wylosujesz dowolny ruch spośród możliwych. Jak wszystko będzie piękne i **otestowane**, popracujemy nad tchnieniem inteligencji w komputer ;)

2020-10-06 10:38 UTC, tomOsuch commented
Kurcze z mojej strony udało mi się niestety chyba bardziej skomplikować jeśli chodzi o podział na pakiety i klasy odpowiadające za logikę i flow :(. Ale jeden plus jest taki że w końcu gra działa.

2020-10-06 22:19 UTC, marszelun requested changes

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +    private void drawMessage(GraphicsContext gc, String str, double x, double y, double size) {
1. IntelliJ donosi, że wartości parametrów x, y i size są zawsze takie same. Nie muszą więc być parametrami, wystarczy że będą stałymi w kodzie tej metody.
2. Metoda mogłaby trafić do jakieś (może nowej?) klasy w pakiecie `io`.

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +        board.draw(graphicsContext);
Skoro `BoardGame` jest klasą, która coś wizualizuje - może wystarczy podać jej `GraphicsContext` w konstruktorze i nie będzie trzeba go podawać za każdym wywołaniem `draw`?

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +                new EventHandler<MouseEvent>() {
Tutaj możesz użyć zwykłej lambdy, nie musisz tworzyć klasy anonimowej.
```
primaryScene.setOnMouseClicked(e -> {
    if (!board.isOpponentSet())
    ...
```

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +                new EventHandler<MouseEvent>() {
Zauważ, że klasa `EventHandler` ma adnotację `@FunctionalInterface`...

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +                new EventHandler<MouseEvent>() {
Wydziel proszę obsługę kliku do odrębnej klasy. Dzięki temu będzie można potencjalnie ograniczyć ilość pól/zależności /zmiennych w pojedynczej klasie.
`primaryScene.setOnMouseClicked(MouseClickHandler::handle)`

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +        primaryScene.setOnKeyPressed(
Tu podobna uwaga z lambdą i wydzieleniem do osobnej klasy.

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/io/BoardGame.java
> +    public BoardGame(double startX, double startY, double sideLength, double pieceMargin, int sideCount, int startCount) {
Jak masz taki "zbiór" parametrów o podobnym przeznaczeniu (tutaj wszystkie 6 parametrów opisuje jakieś właściwości wizualne), to warto wrzucić to do jednej klasy (np. `BoardVisualSettings`), przekazywać tylko ten jeden obiekt jako argument. Dodatkowy plus - będziesz miał o 5 pól mniej w `BoardGame`, znacznie łatwiej będzie to czytać :)

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/io/BoardGame.java
> +        board = new Board(sideCount, startCount);
Obiekt "graficzny" tworzy obiekt "logiczny". Tak nie powinno być. Obiekt logiczny powinien być w stanie zapewnić pełną funkcjonalność gry bez obecności obiektu graficznego. Czyli powinien być raczej przekazany w konstruktorze, niż tutaj tworzony.

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/io/BoardGame.java
> +    private List<BoardPosition> getStrikesCrown(BoardPosition from) {
Szczerze powiedziawszy, szczegółowe zrozumienie tej metody wymaga heroizmu.
Gdy w pracy natkniemy się na taki kod i musimy go zmienić, podchodzimy następująco:
- ustalamy, co ta metoda właściwie ma robić, jaka jest jej odpowiedzialność,
- piszemy do niej testy, szczególnie uwzględniając wszystkie przypadki brzegowe, jakie jesteśmy w stanie wymyśleć,
- kawałek po kawałku refaktorujemy metodę, po każdej małej zmianie odpalamy testy.

W tym miejscu chciałbym jeszcze bardziej zaakcentować, jak testy są **ważne** dla długofalowego utrzymania i rozwoju aplikacji. Ich brak to w bardziej złożonych projektach po prostu samobójstwo.

2020-10-06 22:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/io/Piece.java
> +public class Piece {
Pionki idealnie da się zamodelować hierarchią klas:
`BlackCrown extends BlackPiece extends Piece`
`WhiteCrown extends WhitePiece extends Piece`

Dzięki temu unikniesz większości `if`-ów w tym kodzie, po prostu każda klasa miałaby nieco inną implementację metody `draw`.

2020-10-11 09:56 UTC, tomOsuch commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +        board.draw(graphicsContext);
Nie wiem dlaczego ale jeśli przeniosę GC do klasy `BoardGame` i podam w konstruktorze to niestety nie jest rysowana plansza. oczywiście przeniosłem również komponent `Canvas canvas = new Canvas(700, 700);`

2020-10-11 14:19 UTC, marszelun commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +        board.draw(graphicsContext);
Pokaż to w kodzie - możesz odbić się z aktualnego brancha na nowy i zrobić PR z tego nowego na `checkers-dev`.

2020-10-11 14:54 UTC, tomOsuch commented on src/main/java/com/kodilla/checkers/CheckersApp.java
> +        board.draw(graphicsContext);
Pomyłka popracowałem nad tym i przeniesienie GC do `BoardGame` zadziałało wiec jest ok ;)

2020-10-21 10:58 UTC, merged